version: "3.9"

services:
  ##########################
  # Database
  ##########################
  postgres-prism:
    image: postgres:13
    environment:
      POSTGRES_MULTIPLE_DATABASES: "pollux,connect,agent,node_db"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-db-prism:/var/lib/postgresql/data
      - ./postgres/init-script.sh:/docker-entrypoint-initdb.d/init-script.sh
      - ./postgres/max_conns.sql:/docker-entrypoint-initdb.d/max_conns.sql
    ports:
      - "${PG_PORT:-5433}:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "agent" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      postgres-prism:
        condition: service_healthy

  ##########################
  # Services
  ##########################

  prism-node:
    image: ghcr.io/input-output-hk/prism-node:${PRISM_NODE_VERSION}
    environment:
      NODE_PSQL_HOST: postgres-prism:5432
      NODE_PSQL_DATABASE: node_db
      NODE_PSQL_USERNAME: postgres
      NODE_PSQL_PASSWORD: postgres
      NODE_REFRESH_AND_SUBMIT_PERIOD:
      NODE_MOVE_SCHEDULED_TO_PENDING_PERIOD:
      NODE_WALLET_MAX_TPS:
      NODE_LEDGER: cardano
      NODE_CARDANO_NETWORK: testnet
      NODE_CARDANO_WALLET_API_HOST: ${DOCKERHOST}
      NODE_CARDANO_WALLET_API_PORT: 7090
      #NODE_CARDANO_WALLET_ROUTING_HEADER_NAME="Prism Wallet"
      NODE_CARDANO_DB_SYNC_HOST: ${DOCKERHOST}:5432
      NODE_CARDANO_DB_SYNC_DATABASE: cexplorer
      NODE_CARDANO_DB_SYNC_USERNAME: postgres
      NODE_CARDANO_DB_SYNC_PASSWORD: v8hlDV0yMAHHlIurYupj
      NODE_CARDANO_WALLET_ID: ${WALLET_ID}
      NODE_CARDANO_WALLET_PASSPHRASE: ${WALLET_PASSPHRASE}
      NODE_CARDANO_PAYMENT_ADDRESS: ${WALLET_PAYMENT_ADDR}

    depends_on:
      postgres-prism:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"

  vault-server:
    image: hashicorp/vault:latest
    # ports:
    #   - "8200:8200"
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_DEV_ROOT_TOKEN_ID}
    command: server -dev -dev-root-token-id=${VAULT_DEV_ROOT_TOKEN_ID}
    cap_add:
      - IPC_LOCK
    healthcheck:
      test: [ "CMD", "vault", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5

  prism-agent:
    image: ghcr.io/input-output-hk/prism-agent:${PRISM_AGENT_VERSION}
    environment:
      POLLUX_DB_HOST: postgres-prism
      POLLUX_DB_PORT: 5432
      POLLUX_DB_NAME: pollux
      POLLUX_DB_USER: postgres
      POLLUX_DB_PASSWORD: postgres
      CONNECT_DB_HOST: postgres-prism
      CONNECT_DB_PORT: 5432
      CONNECT_DB_NAME: connect
      CONNECT_DB_USER: postgres
      CONNECT_DB_PASSWORD: postgres
      AGENT_DB_HOST: postgres-prism
      AGENT_DB_PORT: 5432
      AGENT_DB_NAME: agent
      AGENT_DB_USER: postgres
      AGENT_DB_PASSWORD: postgres
      DIDCOMM_SERVICE_URL: http://${DOCKERHOST}:${PORT}/didcomm
      REST_SERVICE_URL: http://${DOCKERHOST}:${PORT}/prism-agent
      PRISM_NODE_HOST: prism-node
      PRISM_NODE_PORT: 50053
      VAULT_ADDR: ${VAULT_ADDR:-http://vault-server:8200}
      VAULT_TOKEN: ${VAULT_DEV_ROOT_TOKEN_ID:-root}
      SECRET_STORAGE_BACKEND: postgres
      DEV_MODE: "true"
      DEFAULT_WALLET_ENABLED: "true"
      DEFAULT_WALLET_SEED:
      DEFAULT_WALLET_WEBHOOK_URL:
      DEFAULT_WALLET_WEBHOOK_API_KEY:
      DEFAULT_WALLET_AUTH_API_KEY:
      GLOBAL_WEBHOOK_URL:
      GLOBAL_WEBHOOK_API_KEY:
      WEBHOOK_PARALLELISM:
      ADMIN_TOKEN:
      API_KEY_SALT:
      API_KEY_ENABLED: "false"
      API_KEY_AUTHENTICATE_AS_DEFAULT_USER:
      API_KEY_AUTO_PROVISIONING:
    depends_on:
      postgres-prism:
        condition: service_healthy
      prism-node:
        condition: service_started
      vault-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://prism-agent:8085/_system/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    extra_hosts:
      - "host.docker.internal:host-gateway"

  swagger-ui:
    image: swaggerapi/swagger-ui:v5.1.0
    environment:
      - 'URLS=[ { name: "Prism Agent", url: "/docs/prism-agent/api/docs.yaml" } ]'

  apisix:
    image: apache/apisix:2.15.0-alpine
    volumes:
      - ./apisix/conf/apisix.yaml:/usr/local/apisix/conf/apisix.yaml:ro
      - ./apisix/conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    ports:
      - "${PORT}:9080/tcp"
    depends_on:
      - prism-agent
      - swagger-ui

volumes:
  postgres-db-prism:
  pgadmin:


networks:
  default:
    name: ${NETWORK}
